### ISSUE TITLE
A separate template-path for a special program

### ISSUE THREAD

**Issue by UnitedMarsupials** [pellcorp/appassembler#1]
Though it makes sense, that the `<unixScriptTemplate>` and friends are specified once and for all by default, some programs may be special enough to warrant a separate custom template.

Yet, currently, setting the `<unixScriptTemplate>` inside a `<program>` is rejected...

**Comment by pellcorp** [comment]
I am not the author of this, I copied it from Codehaus (I don't know why I did not note that in readme), and I have not used this plugin for like 4 years, you should check out

https://github.com/mojohaus/appassembler/tree/master/appassembler-maven-plugin
